In [1]:
from fase import pycrypto

import numpy as np

from fase.core.palisade_bfv import PalisadeBFVContext

# Palisade BGV Test

### BFV Context

In [2]:
plaintextModulus = 536903681
sigma = 3.2
numAdds = 0
numMults = 3
numKeyswitches = 0
maxdepth = 3

context = PalisadeBFVContext(plaintextModulus,
                             numAdds,
                             numMults,
                             numKeyswitches)

#### Input conversion
1) a list of integers  
2) a ndarray of integers and  
3) a ndarray of float containig only exact integer values   
are convertible to a list of integers.  
But 1.1 can't be unambiguously converted to an integer and raises an error.

In [7]:
ctxt1 = context.encrypt([1,2,3,4])
ctxt2 = context.encrypt(np.array([1,2,3,4]))
ctxt3 = context.encrypt(np.array([1.,2.,3.,4.]))
ctxt4 = context.encrypt([1,2,3.,4.])
#ctxt5 = context.encrypt(np.array([1.1,2.,3.,4.]))

In [11]:
res = context.decrypt(ctxt1)
print(res[:5])

[1 2 3 4 0]


### Basic operations

In [12]:
# Addition
ctxt3 = context.add(ctxt1, ctxt2)
print(context.decrypt(ctxt3)[:5])

# Mult & Mult by Plain
ctxt3 = context.mult(ctxt1, ctxt2)
ctxt4 = context.multByVec(ctxt1, [5,4,3,2])

print(context.decrypt(ctxt3)[:5])
print(context.decrypt(ctxt4)[:5])

[2 4 6 8 0]
[ 1  4  9 16  0]
[5 8 9 8 0]


### Rotation

In [13]:
# Trying to rotate before generating rotation key
crot1 = context.rot(ctxt3, 2)
print(context.decrypt(crot1)[:5])

AssertionError: rotation key for 2 not ready

In [7]:
# generate rotation key and try again
context.add_rotKey([-3,-2,-1,1,2,3])
crot1 = context.rot(ctxt3, 2)
print(context.decrypt(crot1)[:5])

[9, 16, 0, 0, 0]
