In [6]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


# Palisade BGV Test

### BGV Context

In [1]:
import numpy as np

from fase.core.palisade_bgv import PalisadeBGVContext

plaintextModulus = 536903681
sigma = 3.2
multDepth = 3
maxdepth = 3

context = PalisadeBGVContext(plaintextModulus,
                             multDepth,
                             maxdepth, 
                             sigma,
                             )

list of integers or ndarray of integers, or integers in float format are supported.  
But real number that can't unambiguosly converted to int is NOT supported

In [2]:
ctxt1 = context.encrypt([1,2,3,4])
ctxt2 = context.encrypt(np.array([1,2,3,4]))
ctxt3 = context.encrypt(np.array([1.,2.,3.,4.]))
print("No Error")

No Error


In [3]:
print("Will raise an error")
ctxt4 = context.encrypt(np.array([1.1,2.,3.,4.]))

Will raise an error


ValueError: Only a list of integers is allowed

### Basic operations

In [4]:
res = context.decrypt(ctxt1)
print(res[:5])
ctxt3 = context.add(ctxt1, ctxt2)

print(context.decrypt(ctxt3)[:5])

# Mult & Mult by Plain
ctxt3 = context.mult(ctxt1, ctxt2)
ctxt4 = context.multByVec(ctxt1, [5,4,3,2])

print(context.decrypt(ctxt3)[:5])
print(context.decrypt(ctxt4)[:5])

[1 2 3 4 0]
[2 4 6 8 0]
[ 1  4  9 16  0]
[5 8 9 8 0]


### Rotation

In [5]:
# Trying to rotate before generating rotation key
print("Can't rotate until rotation keys are ready")
crot1 = context.rot(ctxt3, 2)
print(context.decrypt(crot1)[:5])

Can't rotate until rotation keys are ready


AssertionError: rotation key for 2 not ready

In [7]:
# generate rotation key and try again
context.add_rotKey([-3,-2,-1,1,2,3])
crot1 = context.rot(ctxt3, 2)
print(context.decrypt(crot1)[:5])

print("rotation working")

[ 9 16  0  0  0]
rotation working


### BFV: encrypt, decrypt, add, mult, rotation all work correctly!