In [4]:
import numpy as np 
import torch
from torch import nn

In [2]:
tt = torch.Tensor([np.arange(4), np.arange(1,5), np.arange(2,6)])

/tmp/ipykernel_510474/1667822165.py:1: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  /opt/conda/conda-bld/pytorch_1634272204863/work/torch/csrc/utils/tensor_new.cpp:201.)
  tt = torch.Tensor([np.arange(4), np.arange(1,5), np.arange(2,6)])


In [3]:
tt

tensor([[0., 1., 2., 3.],
        [1., 2., 3., 4.],
        [2., 3., 4., 5.]])

In [8]:
fc1 = nn.Linear(4, 5, bias=True)

In [10]:
fc1.weight

Parameter containing:
tensor([[ 0.3798, -0.4213,  0.2521,  0.0033],
        [-0.1171, -0.4543,  0.1561,  0.1094],
        [-0.2132,  0.3703,  0.0283, -0.4095],
        [ 0.1693, -0.0315,  0.1906,  0.0009],
        [-0.1772, -0.3147,  0.2925,  0.1102]], requires_grad=True)

In [9]:
fc1(tt)

tensor([[-0.1546,  0.3140, -1.0286, -0.0135,  0.3454],
        [ 0.0592,  0.0081, -1.2526,  0.3157,  0.2563],
        [ 0.2730, -0.2977, -1.4767,  0.6449,  0.1671]],
       grad_fn=<AddmmBackward0>)

In [12]:
fc1.bias

Parameter containing:
tensor([-0.2474,  0.1279, -0.2272, -0.3657, -0.2555], requires_grad=True)

In [11]:
-0.4213 + 2*0.2521 + 3*0.0033

0.09279999999999997

In [20]:
w = fc1.weight.detach().numpy()

x = tt.detach().numpy()

b = fc1.bias.detach().numpy()

In [21]:
np.matmul(x, w.T) + b

array([[-0.15463936,  0.3140058 , -1.0286276 , -0.01346123,  0.34543788],
       [ 0.0591796 ,  0.00813413, -1.2526481 ,  0.3157277 ,  0.25625777],
       [ 0.2729985 , -0.29773754, -1.4766684 ,  0.6449167 ,  0.16707772]],
      dtype=float32)

In [23]:
import pickle

In [24]:
mat = pickle.load(open("AfterConv5.picle", "rb"))
fc1 = pickle.load(open("fc1.pickle", "rb"))

org_tt9 = pickle.load(open("org_tt9.pickle", "rb"))

ww, bb = fc1

In [ ]:
org_tt